In [1]:
import numpy as np
a = np.array([1,2,3,4])
print(a.transpose())

[1 2 3 4]


In [2]:
import numpy as np
a = np.array([[1,2,3,4]])
print(a)
print(a.T)

[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


In [3]:
u = np.array([[1,2,3]])
v = np.array([[5,6,7]])
print(u.T + v.T)

[[ 6]
 [ 8]
 [10]]


In [4]:
print(3 * u.T)

[[3]
 [6]
 [9]]


In [5]:
A = np.array([[1,2],
              [3,4],
              [5,6],
              [7,8]])
print(A)
print(A.shape)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)


In [6]:
A = np.array([[1,1,1,1],
              [2,2,2,2],
              [3,3,3,3],
              [4,4,4,4]])
print(A.shape)

(4, 4)


In [7]:
A = np.array([[1,2,3,4],
              [5,6,7,8]])
print(A)
print(A.T)
print(np.transpose(A))

[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [8]:
A = np.zeros([5,3])
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
A = np.diag([1,2,3,4,5])
print(A)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [14]:
I = np.eye(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
x = np.array([[4,5]]).T
A = np.array([[1,2],
              [3,4],
              [5,6]])
print(np.dot(A,x))

[[14]
 [32]
 [50]]


In [20]:
A1 = np.array([[1,1,0],
               [1,0,-1]])
A2 = np.array([[1,2,-1],
               [2,4,-2]])
A3 = np.array([[1,0],
               [0,1],
               [0,-1]])
A4 = np.array([[1,2],
               [1,2],
               [-1,-2]])
A5 = np.array([[1,1,1],
               [1,1,2],
               [1,2,3]])
print(np.linalg.matrix_rank(A1))
print(np.linalg.matrix_rank(A2))
print(np.linalg.matrix_rank(A3))
print(np.linalg.matrix_rank(A4))
print(np.linalg.matrix_rank(A5))

2
1
2
1
3


In [24]:
from scipy import linalg
A_n = linalg.inv(A5)
print(A_n)
print(np.dot(A5,A_n))

[[ 1.  1. -1.]
 [ 1. -2.  1.]
 [-1.  1.  0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
